### ISSUE TITLE
How to implement pause/play through "space" while is not focus on player

### ISSUE THREAD

**Issue by FrankBATMAN** [video-react/video-react#184]
### Issue description

when i choosed the player, "space" key will make video play or pause.
when i not choosed the player, click the web other component, "space" is not work.

### Expected behaviour
i want to make the "space" work in the whole web, not only when choosing the player

is there a possible way?

**Comment by mondaychen** [comment]
You'll need to write your own event handler on the whole document. You can add the player to react `refs`, and then bind a keyboard event in componentDidMount.

```
// in componentDidMount
document.addEventListener('keydown', (e) => {
  if (e.keyCode === 32) { this.ref.player.pause(); }
})
```

It's not recommended to bind things on the document. You'll need to be very careful (e.g. handle special case such as text input) so that you won't break other things on the page.
