### ISSUE TITLE
How does seeking work in a long video?

### ISSUE THREAD

**Issue by cinjon** [video-react/video-react#270]
I have videos that are potentially on the order of 2-3 hours. However, each video is a combination of many segments, each of which are 1-2 minutes long. I know where the start and end of each of those segments are, and I would like to not have to cut the larger video up into those smaller pieces. How would this work with VideoJS? If, upon having the user load the video, the front end immediately used seek to traverse to the intended time, would VideoJS still try to load the entire video? Is there a way to prevent that? 

Thanks!

**Comment by mondaychen** [comment]
I think your question is more about how to stream a large video file, rather than about video-react. As long as you set up your server correctly, there's no need to worry about frontend.

This post might be helpful https://stackoverflow.com/questions/10328401/html5-how-to-stream-large-mp4-files

 I'll close it now.
