### ISSUE TITLE
BigPlayButton Arrests Keyboard

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#41]
Hello again,
We're start open testing of our app tomorrow and just uncovered this bug. Be appreciated if you can find a quick solution :)

An alternative would disabling the `BigPlayButton` and autoShowing the `ControlBar` - right now it only shows once the video starts.

### Issue description
Using the big play button to play the video subsequently arrests the 'space bar' on the keyboard, resulting in each time the space bar is pressed, the video play/pause state toggles. 

Users in my app submit feedback to the video - so if the first thing they do is pay the video (natural thing to do), when they then try add comments they cannot because each time the space bar is pushed, the video plays/pauses.

However, if I activate the play from via method `play()`, before the user hits the big play, this does not happen.

- version `#0.8.5`
- browser: `Safari latest`

### Steps to reproduce issue
1. Install the app, hit the BigPlay button, hit the spacebar on your keyboard.
2. Install the app, trigger a play via the play() method, hit the bar on your keyboard

### Expected behaviour
Hitting the BigPlayButton should not tie spacebar keyboard stroke to toggle play, or should be an option.

### Actual behaviour
Hitting the BigPlayButton  ties spacebar keyboard stroke to toggle play and cannot be disabled. Or can it??

Thank you!
Paola

### Demo
You can fork from this template and add your code
https://jsfiddle.net/jimliu/wcnqzwgs/

**Comment by JimLiu** [comment]
Hi @paolavness 

I'm not sure if I understand your question right.

Video-React handles all the keyboard events in the `Shortcut` component, but it arrests keyboard only if the current player is active. This is the code:
https://github.com/video-react/video-react/blob/master/src/components/Shortcut.js#L242

If the user clicks on the big play button, the player would be in active.

The big play button could be disabled, https://video-react.js.org/customize/enable-disable-components/

**Comment by SampsonCrowley** [comment]
@paolavness that is what is supposed to happen with html5 video. open netflix and try it, or hulu, or amazon video, google play, youtube, vimeo, etc..

What you are asking for is non standard. if you don't want the spacebar to pause, then change the focus after click

**Comment by blaynem** [comment]
@SampsonCrowley that's fine, the issue is actually once the big play button is pressed, if you click off the player and go to type something into a text field, the player reacts to the space and other buttons. Here's a better explanation!

Pauses on key presses (we do not like this behavior):
1. Open page with video
2. Press big play button
3. Move cursor over text input field, click text input field, begin typing
4. Video pauses/plays/skips when keys are pressed

Does NOT pause on keypress (this is correct functionality):
1. Open page with video
2. Press big play button
3. Press on video one more time
4. Move cursor over text input field, click text input field, begin typing
5. Video does not pause/play/skip when typing

Right now we're going through our code to see if it's a way we set it up incorrectly. If anyone has a better suggestion, that'd be great!

**Comment by blaynem** [comment]
@JimLiu if you take a look at my response above this comment it goes into a bit more detail!

**Comment by paolavness** [comment]
@JimLiu we're launching next week, do you think you'll be able to find a solution by then? Basically, as @blaynem explained, clicking directly on the big play button steals keyboard focus, even when you click off the player (on to the screen, in textarea, etc.)

In this case, big play button refers to the <BigPlayButton /> and the big play button visible when <BigPlayButton /> is not used. 

A temporary solution is hiding the <BigPlayButton />. However, the `<ControlBar autoHide={false}>` is not visible, despite `autoHide={false}` 

I look forward to hearing from you,
Paola

**Comment by JimLiu** [comment]
It's a bug, I've fixed it, and I'll publish a new version soon.

**Comment by paolavness** [comment]
@JimLiu thank you so much!
