### ISSUE TITLE
unable to resolve redux module

### ISSUE THREAD

**Issue by spyworldxp** [video-react/video-react#54]
Webpack unable to resolve redux. Because the packages directory is react-redux. To solve this issue, please replace `react-redux` to `redux` in the packages.json

- version `#0.9.8`
- webpack: `2.0`

```
ERROR in ./~/video-react/lib/Manager.js
Module not found: Error: Can't resolve 'redux/lib/createStore' in '/project/app/node_modules/video-react/lib'
```

**Comment by JimLiu** [comment]
Please verify if with v0.8.10

**Comment by jozanza** [comment]
If it's not listed as a `dependency`, and you attempt to use it in a project that does not have `redux`, it will not work.

At the moment, `redux` is only listed as as `peerDependency` and a `devDependency`. 

Since this video player could very well be used in non-redux apps, I think you might want to consider moving `redux` into the `dependencies` section of `package.json` @JimLiu.

**Comment by JimLiu** [comment]
@jozanza 
If I move it to dependencies, redux might be compiled into the bundle in two times.
